NDefines.NGame.START_DATE = "1402.3.12"
NDefines.NGame.END_DATE = "1836.1.2"
NDefines.NCountry.HRE_MAX_RANK = 2
NDefines.NCountry.LIBERTY_DESIRE_DEVELOPED_IN_SUBJECT = 0
NDefines.NCountry.MAX_CROWN_COLONIES = 3
NDefines.NReligion.MAX_CHRISTIAN_RELIGIOUS_CENTERS = 4
NDefines.NReligion.MAX_CARDINALS = 60										-- Max amount of cardinals
NDefines.NReligion.MAX_CARDINALS_PER_COUNTRY = 10							-- Max cardinals in a single country
NDefines.NReligion.REFORM_DESIRE_PER_YEAR = 0.003
